apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-postgresql-deploy-svc.yaml
  - 02-keyclaok-deploy-svc-route.yaml
  - 03-keycloak-job.yaml
  - 04-coolstore-app.yaml

configMapGenerator:
  - name: eap-jms-cli
    files:
      - jms.cli 
  - name: keycloak-realm
    files:
      - realm-export.json

generatorOptions:
  disableNameSuffixHash: true
